name: Keep Backend Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        run: curl -s https://jia-sharebnb-backend.onrender.com > /dev/null
